# Generated by Django 5.0 on 2024-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
    ]
