# Generated by Django 4.2.7 on 2023-11-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('category', models.CharField(choices=[('Elektronika', 'Elektronika'), ('Maishiy_texnika', 'Maishiy_texnika'), ('Noutbooklar', 'Noutbooklar'), ('Smartfonlar', 'Smartfonlar'), ('Planshetlar', 'Planshetlar')], max_length=250)),
                ('color', models.CharField(max_length=13)),
                ('image', models.ImageField(upload_to='rasmlar/')),
                ('time', models.DateTimeField(auto_now=True)),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=10)),
                ('pro_x', models.CharField(choices=[('is_buy', 'is_buy'), ('is_like', 'is_like')], max_length=50)),
            ],
        ),
    ]
