# Generated by Django 4.2.7 on 2023-11-11 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('fulname', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamini +998XXXXXXXXX kabi kiriting!', regex='d{0,9}')])),
                ('password', models.CharField(max_length=20, null=True)),
                ('otp', models.CharField(max_length=4, null=True)),
                ('idp', models.CharField(max_length=9, null=True)),
                ('seria', models.CharField(max_length=2, null=True)),
                ('raqam', models.CharField(max_length=7, null=True)),
                ('pasport', models.FileField(blank=True, null=True, upload_to='pasports/')),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('card', models.CharField(blank=True, max_length=4, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('viloyat', models.CharField(blank=True, choices=[('Toshkent', 'Toshkent'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro')], default='Toshkent', max_length=30, null=True)),
            ],
        ),
    ]
