# Generated by Django 4.2.7 on 2023-11-30 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('fulname', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamini +998XXXXXXXXX kabi kiriting!', regex='d{0,9}')])),
                ('password', models.CharField(max_length=20, null=True)),
                ('otp', models.CharField(max_length=4, null=True)),
                ('idp', models.CharField(max_length=9, null=True)),
                ('seria', models.CharField(max_length=2, null=True)),
                ('raqam', models.CharField(max_length=7, null=True)),
                ('pasport', models.FileField(blank=True, null=True, upload_to='pasports/')),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('card', models.CharField(blank=True, max_length=4, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('viloyat', models.CharField(blank=True, choices=[('Toshkent', 'Toshkent'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro')], default='Toshkent', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamini +9989XXXXXXXX kabi kiriting!', regex='d{0,9}')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Kodni kiritishlar soni:')),
                ('validated', models.BooleanField(default=False, help_text='Shaxsiy kabinetingizni yaratishingiz mumkin!')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9, unique=True)),
                ('verify_code', models.SmallIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('step_reset', models.CharField(blank=True, choices=[('send', 'send'), ('confirmed', 'confirmed')], max_length=10, null=True)),
                ('step_change_phone', models.CharField(blank=True, choices=[('send', 'send'), ('confirmed', 'confirmed')], max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('buyurtma_berish', 'buyurtma_berish'), ('buyurtma_tayyorlanmoqda', 'buyurtma_tayyorlanmoqda'), ('yetkazib_berish_jarayoni', 'yetkazib_berish_jarayoni'), ('yetkazilgan', 'yetkazilgan'), ('bekor_qilingan', 'bekor_qilingan')], default='buyurtma_berish', max_length=200)),
                ('payment', models.CharField(choices=[('naqt', 'naqt'), ('card', 'card'), ('credit', 'credit')], default='naqt', max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=10, null=True)),
                ('pro_x', models.CharField(choices=[('is_buy', 'is_buy'), ('is_like', 'is_like')], max_length=50, null=True)),
                ('oy_cre', models.CharField(choices=[('6', '6'), ('12', '12'), ('24', '24')], default='6', max_length=50, null=True)),
                ('phone_cre', models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamini +998XXXXXXXXX kabi kiriting!', regex='d{0,9}')])),
                ('tasdiq', models.BooleanField(default=False, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
