# Generated by Django 4.2.7 on 2023-11-11 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamini +9989XXXXXXXX kabi kiriting!', regex='d{0,9}')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Kodni kiritishlar soni:')),
                ('validated', models.BooleanField(default=False, help_text='Shaxsiy kabinetingizni yaratishingiz mumkin!')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9, unique=True)),
                ('verify_code', models.SmallIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('step_reset', models.CharField(blank=True, choices=[('send', 'send'), ('confirmed', 'confirmed')], max_length=10, null=True)),
                ('step_change_phone', models.CharField(blank=True, choices=[('send', 'send'), ('confirmed', 'confirmed')], max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
