# Generated by Django 5.0 on 2024-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tasdiq',
            field=models.BooleanField(null=True),
        ),
    ]
