# Generated by Django 4.2.7 on 2023-11-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_about_alter_product_category_and_more'),
        ('User', '0002_validatedotp_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('buyurtma_berish', 'buyurtma_berish'), ('buyurtma_tayyorlanmoqda', 'buyurtma_tayyorlanmoqda'), ('yetkazib_berish_jarayoni', 'yetkazib_berish_jarayoni'), ('yetkazilgan', 'yetkazilgan'), ('bekor_qilingan', 'bekor_qilingan')], default='buyurtma_berish', max_length=200)),
                ('payment', models.CharField(choices=[('naqt', 'naqt'), ('card', 'card'), ('credit', 'credit')], default='naqt', max_length=100)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
