# Generated by Django 4.2.7 on 2023-11-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
